### ISSUE TITLE
Замечания по JS

### ISSUE THREAD

**Issue by Droidion** [redaktorscha/task-3#16]
1. Сейчас id кнопок задаются в двух местах: в html и js файлах. То есть они повторяются. Повторений лучше избегать. id можно оставить только в html, а в js получать id динамически через getElementsByClassName, присвоив в html кнопках дополнительный класс.
Собственно, эта же идея уже реализована для текста кнопки! Можно использовать тот же подход и для id

2. id кнопок сейчас хранятся в js файле два раза. Один раз статически в константе counters,
а второй раз динамически в массиве keys. Это избыточно, нужно ограничиться одним местом хранения.

3. Сейчас каждая кнопка инциализируется своим отдельным нулем. По условиям задачи это тоже избыточно.
Лучше инициализировать начальной значение счетчика для каждого id в цикле, прописав 0 в коде ровно один раз в теле цикла.

4. let elems - плохое имя, тут же один элемент. Лучше elem

5. Лучше привыкать к современному синтаксису объявления функций. Перед каждой функцией ВСЕГДА должен быть комментарий, что эта функция делает и какие параметры принимает какого типа. Синтаксис такой: Сначала первой строчкой пишется, что функция делает. Потом перечисляются параметры. У нас один параметр: btn. Пишет кодовое слово @param - это значит, что сейчас расскажем про параметр. Дальше через пробел название параметра. Дальше через пробел тип передаваемого параметра. Например, number или string. В нашем случае - это объект (Object). Потом через пробел объяснение, что этот параметр значит.
```
// Увеличивает счетчик конкретной кнопки
// @param btn Object Кнопка, на которую пользователь нажал
const count = (btn) => {
  ...
}
```

6. В конце работы код лучше прогонять через автоматическое форматирование (Команда в VS Code 'Format Document')
Команды вызываются через ctrl+shift+p

**Comment by redaktorscha** [comment]
done
